### ISSUE TITLE
Regarding critical issues.

### ISSUE THREAD

**Issue by NotANormie** [CyberDiscovery/Cyber-Discovery-App#1]
Remove Google analytics and licence it under a copyleft licence and I wont kill myself.

(also would be nice if you could include a social feed of the CD twitter or medium)

Thanks.

**Comment by REDACTED-REDACTED** [comment]
The only thing the analytics package is used for is recording which sounds are played so I can make pwitty graphs. The rest of the analytical data collected is sadly a required part of using firebase.  I'm fine with a license do you have any suggestions?
