### ISSUE TITLE
Countdown text is too large for smaller screens

### ISSUE THREAD

**Issue by REDACTED-REDACTED** [CyberDiscovery/Cyber-Discovery-App#21]
Text is too wide resultsing in the text being put onto two lines

![example](https://cdn.discordapp.com/attachments/411573884597436416/475788163550412800/Screenshot_2018-08-05-23-10-32.png)

**Comment by Bentechy66** [comment]
Can confirm that this does not fix the issue, still occurring on iPhone 5s - A possible solution would be to adopt the words "mins" and "secs" in place of "minutes" and "seconds" - This may even be considered more stylish
