### ISSUE TITLE
Auto Update

### ISSUE THREAD

**Issue by REDACTED-REDACTED** [CyberDiscovery/Cyber-Discovery-App#8]
The app should detect when a new version is released and prompt the user to start the download and install process. (Android Only)

**Comment by thebeanogamer** [comment]
Whilst I do think the update notifacation is a good idea, in my opinion we
should hold off until the app is on Google Play and can be downloaded from
there, to save us building a system and replacing it soon after. --

Daniel Milnes

**Comment by REDACTED-REDACTED** [comment]
Fair enough
